### ISSUE TITLE
Coverage fails when a contract interacts with another deployed contract

### ISSUE THREAD

**Issue by JSchwerberg** [MeadowSuite/Meadow#16]
```
Post-test exception: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Meadow.CoverageReport.ReportGenerator.IdentifyExecutedSourceLines(CoverageMap coverageMap, String opcodesString, SourceMapEntry[] sourceMap, AnalysisResults analysis, Dictionary`2 sourceFileMaps, List`1 catchExceptions)
   at Meadow.CoverageReport.ReportGenerator.CreateReport(String solidityCompilerVersion, ValueTuple`2[] coverageMaps, SolcSourceInfo[] sourcesList, SolcBytecodeInfo[] byteCodeData, IGrouping`2[] unitTestOutcome, String[] ignoredSourceFiles, String reportOutputDirectory, List`1 catchExceptions)
   at Meadow.UnitTestTemplate.Global.CleanupInternal(List`1 catchExceptions)
   at Meadow.UnitTestTemplate.Global.GenerateCoverageReport()
```

Seems to occur when a Solidity function is called by a C# test that interacts with another contract unknown to Meadow.

e.g.:

```
# Solidity

Timelock timelock = new Timelock()
timelock.lockUntil(1000000000)
```

**Comment by Xenomega** [comment]
Addressed as this was actually a configuration issue. Coverage cannot be collected when solc has optimizations enabled. Appropriate error handling will be added.
